### ISSUE TITLE
Add a new site to the block list

### ISSUE THREAD

**Issue by dmitry-golovnya** [yarfuo/overshits#1]
found that this site also just copies the answers https://serveanswer.com/
Perhaps there is a way to add the ability to add sites manually to the blocklist?

**Comment by yarfuo** [comment]
Hello! Right now, the blocklist is [loading remotely](https://github.com/yarfuo/overshits/blob/main/src/background.ts#L3) from the repository. The idea of the project is to be like install&beHappy. If you need something difficult, you can use [uBlacklist](https://github.com/iorate/uBlacklist#uBlacklist).

Thank you for your attention to my project.
